name: Generate and Deploy Performance Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Rust environment
        run: |
          sudo apt update
          sudo apt install -y curl
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Run Python and Rust word counts using Makefile
        run: |
          . venv/bin/activate
          make report

      - name: Upload Performance Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: performance-report
          path: performance_report.md

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Commit and Push Report
        env:
          GITHUB_TOKEN: ${{ secrets.IDS_TOKEN }}
        run: |
          git add performance_report.md
          git commit -m "Auto-generate performance report [ci skip]" || echo "No changes to commit"
          git push origin HEAD:main
