name: Generate and Deploy Performance Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Rust environment
        run: |
          sudo apt update
          sudo apt install -y curl
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Run Python word count
        run: |
          . venv/bin/activate
          python word_counter_py/cli.py test.txt > python_results.txt

      - name: Run Rust word count
        run: |
          cd word_counter_rust
          cargo build --release
          ./target/release/word_counter_rust ../test.txt > ../rust_results.txt
          cd ..

      - name: Generate performance comparison report
        run: |
          . venv/bin/activate
          python ./src/generate_comparison_report.py  # Ensure the path is correct and file is in the root directory

      - name: Display Report
        run: cat performance_report.md

  deploy_report:
    runs-on: ubuntu-latest
    needs: generate_report

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Add and Commit report
        run: |
          git add performance_report.md
          git commit -m "Update performance report [ci skip]" || echo "No changes to commit"

      - name: Push report to main branch
        run: |
          git push origin HEAD:main
