name: Generate Performance Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Rust environment
        run: |
          sudo apt update
          sudo apt install -y curl
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Run Python word count
        run: |
          . venv/bin/activate
          python word_counter_py/cli.py test.txt > python_results.txt

      - name: Run Rust word count
        run: |
          cd word_counter_rust
          cargo build --release
          ./target/release/word_counter_rust ../test.txt > ../rust_results.txt
          cd ..

      - name: Generate performance comparison report
        run: |
          . venv/bin/activate
          python ./src/generate_comparison_report.py

      - name: Display Report
        run: cat performance_report.md

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: performance-report
          path: performance_report.md
